# General
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
ignoreFiles:
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_files$"
  - "_cache$"
baseurl: https://codgician.me/
theme: hermit
pygmentsCodefences: true
pygmentsUseClasses: true
hasCJKLanguage: true
copyright: 'This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.'
enableRobotsTXT: true
author:
  name: codgician
permalinks:
  posts: '/posts/:year/:month/:filename/'
enableEmoji: true
googleAnalytics: UA-97035940-1
params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  description: Have a codgistic day!.
  keywords: 'homepage, blog, icpc, oi, development, programming'
  images:
    - ''
  contentTypeName: posts
  themeColor: "#292a2d"
  relatedPosts: false
  social:
    - name: github
      url: 'https://www.github.com/codgician/'
    - name: twitter
      url: 'https://twitter.com/codgician/'
    - name: telegram
      url: 'https://t.me/codgician/'
    - name: email
      url: 'mailto:gutomata@outlook.com'
  code_copy_button: false
  katex: true
  utterances:
    repo: codgician/homepage-comments
    label:
    theme: photon-dark

# Multi-lingual
languages:
  en:
    languageName: English
    languageCode: en
    weight: 1
    title: codgician
    subtitle: 'Coding Magic'
    keywords: ''
    footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>'
    taxonomies:
      category: categories
      tag: tags
    params:
      homeSubtitle: Coding Magic
    menu:
      main:
        - identifier: blog
          name: BLOG
          url: posts/
          weight: 10
        - identifier: icpc
          name: ICPC
          url: icpc/
          weight: 20
        # - identifier: pals
        #   name: PALS 
        #   url: pals/
        #   weight: 30
        - identifier: more
          name: MORE
          url: more/
          weight: 40
  zh-hans:
    languageName: 简体中文
    languageCode: zh-hans
    weight: 2
    title: codgician
    subtitle: '码上就好~'
    keywords: ''
    footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>'
    taxonomies:
      category: categories
      tag: tags
    params:
      homeSubtitle: '码上就好~'
    menu:
      main:
        - identifier: blog
          name: 博客
          url: posts/
          weight: 10
        - identifier: icpc
          name: 竞赛
          url: icpc/
          weight: 20
        # - identifier: pals
        #   name: 朋友
        #   url: pals/
        #   weight: 30
        - identifier: more
          name: 更多
          url: more/
          weight: 40

